package id.ac.poliban.mi.andri.listtarian;

import java.util.ArrayList;
import java.util.List;

public class DataTarian {
    static List<Tarian> getAllTarians() {
        List<Tarian> data = new ArrayList<>();
        {
            data.add(new Tarian("https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Jaipongan.jpg/193px-Jaipongan.jpg","Tari Jaipongan","Jaipongan terlahir melalui proses kreatif dari tangan dingin H. Suanda sekitar tahun 1976 di Karawang, jaipongan merupakan garapan yang menggabungkan beberapa elemen seni tradisi karawang seperti pencak silat, wayang golek, topeng banjet, ketuk tilu dan lain-lain. Jaipongan di karawang pesat pertumbuhannya di mulai tahun 1976, di tandai dengan munculnya rekaman jaipongan SUANDA GROUP dengan instrument sederhana yang terdiri dari gendang, ketuk, kecrek, goong, rebab dan sinden atau juru kawih. Dengan media kaset rekaman tanpa label tersebut (indie label) jaipongan mulai didistribusikan secara swadaya oleh H Suanda di wilayah karawang dan sekitarnya. Tak disangka Jaipongan mendapat sambutan hangat, selanjutnya jaipongan menjadi sarana hiburan masyarakat karawang dan mendapatkan apresiasi yang cukup besar dari segenap masyarakat karawang dan menjadi fenomena baru dalam ruang seni budaya karawang, khususnya seni pertunjukan hiburan rakyat. Posisi Jaipongan pada saat itu menjadi seni pertunjukan hiburan alternative dari seni tradisi yang sudah tumbuh dan berkembang lebih dulu di karawang seperti penca silat, topeng banjet, ketuk tilu, tarling dan wayang golek. Keberadaan jaipong memberikan warna dan corak yang baru dan berbeda dalam bentuk pengkemasannya, mulai dari penataan pada komposisi musikalnya hingga dalam bentuk komposisi tariannya. "));
            data.add(new Tarian("https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/Kecak_Dance_1.jpg/250px-Kecak_Dance_1.jpg","Tari Kecak","Kecak (pelafalan: /'ke.tʃak/, secara kasar \"KEH-chahk\", pengejaan alternatif: Ketjak, Ketjack) adalah pertunjukan dramatari seni khas Bali yang lebih utama menceritakan mengenai Ramayana dan dimainkan terutama oleh laki-laki. Tarian ini dipertunjukkan oleh banyak (puluhan atau lebih) penari laki-laki yang duduk berbaris melingkar dan dengan irama tertentu menyerukan \"cak\" dan mengangkat kedua lengan, menggambarkan kisah Ramayana saat barisan kera membantu Rama melawan Rahwana. Namun, Kecak berasal dari ritual sanghyang, yaitu tradisi tarian yang penarinya akan berada pada kondisi tidak sadar[1], melakukan komunikasi dengan Tuhan atau roh para leluhur dan kemudian menyampaikan harapan-harapannya kepada masyarakat."));
            data.add(new Tarian("https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Tari_topeng_cirebon.jpg/360px-Tari_topeng_cirebon.jpg","Tari Topeng","Tari topeng Cirebon adalah salah satu tarian di wilayah kesultanan Cirebon. Tari Topeng Cirebon, kesenian ini merupakan kesenian asli daerah Cirebon, termasuk Subang, Indramayu, Jatibarang, Majalengka, Losari, dan Brebes. Disebut tari topeng karena penarinya menggunakan topeng di saat menari. Pada pementasan tari Topeng Cirebon, penarinya disebut sebagai dalang, dikarenakan mereka memainkan karakter topeng-topeng tersebut. "));
            data.add(new Tarian("https://upload.wikimedia.org/wikipedia/id/thumb/d/db/Tari_Pakar%C3%A9na.jpg/220px-Tari_Pakar%C3%A9na.jpg","Tari Pakarena","Tari Pakarena adalah tarian tradisional dari Sulawesi Selatan yang diiringi oleh 2 (dua) kepala drum (gandrang) dan sepasang instrument alat semacam suling (puik-puik)[1]. Selain tari pakarena yang selama ini dimainkan oleh maestro tari pakarena Maccoppong Daeng Rannu (alm) di kabupaten Gowa, juga ada jenis tari pakarena lain yang berasal dari Kabupaten Kepulauan Selayar yaitu “Tari Pakarena Gantarang”. Disebut sebagai Tari Pakarena Gantarang karena tarian ini berasal dari sebuah perkampungan yang merupakan pusat kerajaan di Pulau Selayar pada masa lalu yaitu Gantarang Lalang Bata. Tarian yang dimainkan oleh kurang lebih empat orang penari perempuan ini pertama kali ditampilkan pada abad ke 17 tepatnya tahun 1903 saat Pangali Patta Raja dinobatkan sebagai Raja di Gantarang Lalang Bata[2]. "));
            data.add(new Tarian("https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/YanAriefTarianNgajat.jpg/250px-YanAriefTarianNgajat.jpg","Tari Talawang","Talawang adalah tameng atau perisai Suku Dayak yang terbuat dari kayu ulin atau kayu besi.[1] Talawang berbentuk persegi panjang yang dibuat runcing pada bagian atas dan bawahnya. Panjang talawang sekitar 1 sampai dengan 2 meter dengan lebar maksimal 50 centimeter.[1] Sisi luar talawang dihias dengan ukiran yang mencirikan kebudayaan Dayak, sementara bagian dalamnya diberi pegangan.[1] "));
        }

        return data;
    }
}
